services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_ROOT_PASS=${DB_ROOT_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    environment:
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - DOMAIN_NAME=${DOMAIN_NAME}
    - WP_ADMIN_USER=${WP_ADMIN_USER}
    - WP_ADMIN_PASS=${WP_ADMIN_PASS}
    - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    - WP_USER=${WP_USER}
    - WP_USER_PASS=${WP_USER_PASS}
    - WP_USER_EMAIL=${WP_USER_EMAIL}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "443:443"  # ONLY nginx exposes HTTPS
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  adminer:
    build: ./bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
    # NO ports exposed - accessed via nginx proxy
    networks:
      - inception
    restart: always

  redis:
    build: ./bonus/redis
    container_name: redis
    # NO ports exposed - internal communication only
    networks:
      - inception
    restart: always

  static-site:
    build: ./bonus/static-site
    container_name: static-site
    networks:
      - inception
    restart: always

  ftp:
    build: ./bonus/ftp
    container_name: ftp
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    ports:
      - "21:21"                    # FTP protocol exception
      - "21000-21010:21000-21010"  # FTP passive mode ports
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

  filebrowser:
    build: ./bonus/filebrowser
    container_name: filebrowser
    volumes:
      - wordpress_data:/var/www/html:ro
      - filebrowser_data:/config
    networks:
      - inception
    restart: always
  
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/odana/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/odana/data/wordpress
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/odana/data/adminer
  filebrowser_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/odana/data/filebrowser
      
networks:
  inception:
    driver: bridge