services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_ROOT_PASS=${DB_ROOT_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - DOMAIN_NAME=${DOMAIN_NAME}
    - WP_ADMIN_USER=${WP_ADMIN_USER}
    - WP_ADMIN_PASS=${WP_ADMIN_PASS}
    - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    - WP_USER=${WP_USER}
    - WP_USER_PASS=${WP_USER_PASS}
    - WP_USER_EMAIL=${WP_USER_EMAIL}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/odana/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/odana/data/wordpress

networks:
  inception:
    driver: bridge